### PR TITLE
Upgrade jms/serializer

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Is this passing because there are no tests, or because it actually works?

**Comment by tgalopin** [comment]
Tests did run (perhaps with a delay) and pass :) .

**Comment by GrahamCampbell** [comment]
Yeh, I saw. I am wondering if the tests passing is actually an indicator that this upgrade was good. I've not tested my changes work, other than running the test suite.

**Comment by GrahamCampbell** [comment]
I don't have any bandwidth to verify what has broken, if anything. Anyone else is welcome to finish up here. :)

**Pull request closed without merging**
